### PR TITLE
test/cluster: reinstate test on 24.04

### PR DESCRIPTION
**Pull request by simondeziel**
https://bugs.launchpad.net/ubuntu/+source/linux/+bug/2064508 is fixed

### CODE REVIEW

**Comment by simondeziel** [comment]
Still failing as Azure has `-1009` but according to https://bugs.launchpad.net/ubuntu/+source/linux/+bug/2064508, we need `-1010` (`linux-azure-6.8/6.8.0-1010.10~22.04.1`). Maybe later in the week...

**Comment by simondeziel** [comment]
This is currently failing but not due to FAN networking but because the cluster isn't yet ready?

```
+ echo '==> Test fan networking'
+ lxc exec cluster-3413-1 -- lxc launch ubuntu-minimal-daily:24.04 u1
==> Test fan networking
Creating u1
Error: Failed instance creation: No suitable cluster member could be found
```

BTW, the kernel now available on Azure should support FAN.

**Comment by tomponline** [comment]
> This is currently failing but not due to FAN networking but because the cluster isn't yet ready?

Is it working now?

**Comment by simondeziel** [comment]
> > This is currently failing but not due to FAN networking but because the cluster isn't yet ready?
> 
> Is it working now?

Yes it is: https://github.com/canonical/lxd-ci/actions/runs/10255088529/job/28371332491?pr=235 & https://github.com/canonical/lxd-ci/actions/runs/10255088529/job/28371339840?pr=235

```
+ lxc exec cluster-3360-1 -- lxc exec u1 -- timeout 30s bash -c 'grep -m1 ^SSH < /dev/tcp/240.18.0.90/22'
SSH-2.0-OpenSSH_9.6p1 Ubuntu-3ubuntu13.4
+ lxc exec cluster-3360-1 -- timeout 30s bash -c 'grep -m1 ^SSH < /dev/tcp/240.18.0.90/22'
SSH-2.0-OpenSSH_9.6p1 Ubuntu-3ubuntu13.4
```

It's all green as far as this PR is concerned now.

**Review by tomponline — APPROVED** [review]

**Pull request merged**
