### PR TITLE
Adapt VM storage tests to support Dell PowerFlex

### PR DESCRIPTION
**Pull request by roosterfish**
This PR adapts both of the VM storage tests so they can be executed using the Dell PowerFlex storage driver from https://github.com/canonical/lxd/pull/12304.

Storage size values for PowerFlex need to be in multiples of 8GiB. The minimal storage volume size in PowerFlex is also 8GiB. 
Where applicable the storage size of the actual test was increased for all the drivers to accommodate PowerFlex. At other places a different storage size gets set for the PowerFlex driver only.

### CODE REVIEW

**Review by simondeziel — COMMENTED** [review]
I'm fine with the changes but the `tests/storage-vm` goes from ~86 minutes to 115 minutes on PS5 instances. If we care about testing this on OpenStack instances, we might want to tweak the disk sizes like done in `tests/storage-volumes-vm`.

**Review by simondeziel — DISMISSED** [review]
Other than the slower speed of `tests/storage-vm`, things still work as tested on non-powerflex storage driver.

**Comment by tomponline** [comment]
Can we make the larger sizes only be used for the powerflex tests?

**Review by simondeziel — APPROVED** [review]
Thanks!

**Review by tomponline — APPROVED** [review]

**Pull request merged**
