### PR TITLE
Refresh `network-ovn` and make it work without IPv6

### PR DESCRIPTION
**Pull request by simondeziel**
This was successfully ran on PS5.

### CODE REVIEW

**Review by tomponline — APPROVED** [review]
I think later we could rework these tests to use lxdbr0 as an uplink so that we can test ipv6 and DNS to the uplink even if the host itself doesn't have external ipv6 connectivity.

**Comment by simondeziel** [comment]
> I think later we could rework these tests to use lxdbr0 as an uplink so that we can test ipv6 and DNS to the uplink even if the host itself doesn't have external ipv6 connectivity.

In several places, `lxdbr0`'s IPv4/6 are tested like this:

```
ovn_basic_tests() {
    lxc network create lxdbr0 \
        ipv4.address=10.10.10.1/24 ipv4.nat=true \
        ipv4.dhcp.ranges=10.10.10.2-10.10.10.199 \
        ipv4.ovn.ranges=10.10.10.200-10.10.10.254 \
        ipv6.address=fd42:4242:4242:1010::1/64 ipv6.nat=true \
        ipv6.ovn.ranges=fd42:4242:4242:1010::200-fd42:4242:4242:1010::254
...

    echo "==> OVN to lxdbr0 gateway"
    lxc exec u2 -- ping -nc1 -w5 10.10.10.1
    lxc exec u2 -- ping -nc1 -w5 fd42:4242:4242:1010::1
```

Is this what you had in mind?

**Comment by tomponline** [comment]
Yeah and then we can ping a host by name on lxdbr0 from ovn to test external DNS too

**Comment by simondeziel** [comment]
I think all that is done already. I changed some `ping` to use TCP/443 probes due to PS5 outbound firewall but we already have that:

```
    echo "==> lxdbr0 to internet"
    lxc exec u1 -- nc -zv -4 -w5 ubuntu.com 443
    [ "${IPV6_UPLINK}" = "true" ] && lxc exec u1 -- nc -zv -6 -w5 ubuntu.com 443
```

So anything I am missing/misunderstood?

**Comment by tomponline** [comment]
Yes, we dont need to ping externally at all really, all we need to do is check for connectivity to the uplink network.
So we don't need the IPV6_UPLINK var at all.

**Pull request merged**
