### PR TITLE
Fix archlinux images to pass `systemd --failed` test

### PR DESCRIPTION
**Pull request by simondeziel**
Should fix https://github.com/canonical/lxd-ci/actions/runs/9688390234/job/26734859244#step:7:79

### CODE REVIEW

**Review by tomponline — APPROVED** [review]

**Comment by tomponline** [comment]
Do we know what that service does and why it doesn't work?

**Comment by simondeziel** [comment]
> Do we know what that service does and why it doesn't work?

https://www.freedesktop.org/software/systemd/man/latest/systemd-nsresourced.service.html explains it. As to why it doesn't work, maybe due to missing `security.nesting=true`?

**Comment by simondeziel** [comment]
This made the container images build and boot successfully but not the VM. I'll try to do a followup PR once I've reproduced the issue locally.

@MusicDin Arch Linux was last published on June 16th so it's getting close to being purged so I won't mind if you beat me to it ;)

**Comment by MusicDin** [comment]
Yes, same for Kali linux

**Comment by MusicDin** [comment]
> maybe due to missing security.nesting=true

If `security.nesting` is required, we could add it as a requirement?

**Comment by tomponline** [comment]
> > maybe due to missing security.nesting=true
> 
> If `security.nesting` is required, we could add it as a requirement?

It shouldn't be ideally this might be something @mihalicyn should be aware of wrt to his apparmor improvements he's working on.

**Comment by MusicDin** [comment]
Will investigate, but it seems like an issue on LXD side, as many images are now failing the VM tests (Alpine, Gentoo, RockyLinux, ArchLinux, ...)

**Comment by MusicDin** [comment]
For archlinux `systemd-nsresourced.service`:
```
$ journalctl -u systemd-nsresourced.service
Jun 28 10:57:32 ac systemd[1]: Starting Namespace Resource Manager...
Jun 28 10:57:33 ac systemd-nsresourced[399]: Failed to open registry directory: Read-only file system
Jun 28 10:57:33 ac systemd-nsresourced[399]: Failed to start up daemon: Read-only file system
Jun 28 10:57:33 ac systemd[1]: systemd-nsresourced.service: Main process exited, code=exited, status=1/FAILURE
Jun 28 10:57:33 ac systemd[1]: systemd-nsresourced.service: Failed with result 'exit-code'.
Jun 28 10:57:33 ac systemd[1]: Failed to start Namespace Resource Manager.
```

Arch VM issue is secure boot. Disabling secureboot allow VM to boot properly.

**Comment by tomponline** [comment]
Can you see if there are any apparmor warnings?

Also suggest disabling that systemd unit for now

**Comment by MusicDin** [comment]
```
$ lxc init local:a84d4f14e855 arch-vm --vm

[862148.406681] audit: type=1400 audit(1719574440.535:25947): apparmor="STATUS" operation="profile_load" profile="unconfined" name="lxd_archive-var-snap-lxd-common-lxd-storage-pools-default-virtual-machines-arch-vm" pid=2770719 comm="apparmor_parser"
[862148.476847] audit: type=1400 audit(1719574440.603:25948): apparmor="STATUS" operation="profile_remove" profile="unconfined" name="lxd_archive-var-snap-lxd-common-lxd-storage-pools-default-virtual-machines-arch-vm" pid=2770725 comm="apparmor_parser"
[862148.513381] audit: type=1400 audit(1719574440.639:25949): apparmor="STATUS" operation="profile_load" profile="unconfined" name="lxd_qemu-img-<var-snap-lxd-common-lxd-images-a84d4f14e855229a35798d9df49bf7fb2be61e8a531f231d3610594e997973e7.rootfs>_<var-snap-lxd-common-lxd-storage-pools-default-virtual-machines-arch-vm-root.img>" pid=2770729 comm="apparmor_parser"
[862148.526748] audit: type=1400 audit(1719574440.655:25950): apparmor="DENIED" operation="open" profile="lxd_qemu-img-<var-snap-lxd-common-lxd-images-a84d4f14e855229a35798d9df49bf7fb2be61e8a531f231d3610594e997973e7.rootfs>_<var-snap-lxd-common-lxd-storage-pools-default-virtual-machines-arch-vm-root.img>" name="/sys/devices/system/node/" pid=2770730 comm="qemu-img" requested_mask="r" denied_mask="r" fsuid=0 ouid=0
[862148.563878] audit: type=1400 audit(1719574440.691:25951): apparmor="STATUS" operation="profile_remove" profile="unconfined" name="lxd_qemu-img-<var-snap-lxd-common-lxd-images-a84d4f14e855229a35798d9df49bf7fb2be61e8a531f231d3610594e997973e7.rootfs>_<var-snap-lxd-common-lxd-storage-pools-default-virtual-machines-arch-vm-root.img>" pid=2770736 comm="apparmor_parser"
[862148.598211] audit: type=1400 audit(1719574440.727:25952): apparmor="STATUS" operation="profile_load" profile="unconfined" name="lxd_qemu-img-<var-snap-lxd-common-lxd-images-a84d4f14e855229a35798d9df49bf7fb2be61e8a531f231d3610594e997973e7.rootfs>_<var-snap-lxd-common-lxd-storage-pools-default-virtual-machines-arch-vm-root.img>" pid=2770738 comm="apparmor_parser"
[862148.611623] audit: type=1400 audit(1719574440.739:25953): apparmor="DENIED" operation="open" profile="lxd_qemu-img-<var-snap-lxd-common-lxd-images-a84d4f14e855229a35798d9df49bf7fb2be61e8a531f231d3610594e997973e7.rootfs>_<var-snap-lxd-common-lxd-storage-pools-default-virtual-machines-arch-vm-root.img>" name="/sys/devices/system/node/" pid=2770739 comm="qemu-img" requested_mask="r" denied_mask="r" fsuid=0 ouid=0
[862152.692853] audit: type=1400 audit(1719574444.819:25954): apparmor="STATUS" operation="profile_remove" profile="unconfined" name="lxd_qemu-img-<var-snap-lxd-common-lxd-images-a84d4f14e855229a35798d9df49bf7fb2be61e8a531f231d3610594e997973e7.rootfs>_<var-snap-lxd-common-lxd-storage-pools-default-virtual-machines-arch-vm-root.img>" pid=2770797 comm="apparmor_parser"

$ lxc start arch-vm

[862177.929061] lxdbr2: port 5(tap16194183) entered blocking state
[862177.929065] lxdbr2: port 5(tap16194183) entered disabled state
[862177.929119] device tap16194183 entered promiscuous mode
[862178.219718] audit: type=1400 audit(1719574470.347:25955): apparmor="STATUS" operation="profile_load" profile="unconfined" name="lxd-arch-vm_</var/snap/lxd/common/lxd>" pid=2771065 comm="apparmor_parser"
[862178.377629] lxdbr2: port 5(tap16194183) entered blocking state
[862178.377633] lxdbr2: port 5(tap16194183) entered forwarding state

$ lxc stop -f arch-vm

[862205.613383] lxdbr2: port 5(tap16194183) entered disabled state
[862205.853264] device tap16194183 left promiscuous mode
[862205.853324] lxdbr2: port 5(tap16194183) entered disabled state
[862206.079132] audit: type=1400 audit(1719574498.208:25956): apparmor="STATUS" operation="profile_remove" profile="unconfined" name="lxd-arch-vm_</var/snap/lxd/common/lxd>" pid=2771429 comm="apparmor_parser"

$ lxc config set arch-vm security.secureboot=false
$ lxc start arch-vm

[862232.704812] lxdbr2: port 5(tap027a88f1) entered blocking state
[862232.704816] lxdbr2: port 5(tap027a88f1) entered disabled state
[862232.704866] device tap027a88f1 entered promiscuous mode
[862232.836682] audit: type=1400 audit(1719574524.968:25957): apparmor="STATUS" operation="profile_load" profile="unconfined" name="lxd-arch-vm_</var/snap/lxd/common/lxd>" pid=2771802 comm="apparmor_parser"
[862232.959660] lxdbr2: port 5(tap027a88f1) entered blocking state
[862232.959665] lxdbr2: port 5(tap027a88f1) entered forwarding state
```

**Comment by MusicDin** [comment]
Found the issue, we were not disabling secureboot for specific images: https://github.com/canonical/lxd-ci/pull/217

Sorry for noise

**Pull request merged**
