### PR TITLE
CI tweaks

### PR DESCRIPTION
**Pull request by simondeziel**

### CODE REVIEW

**Comment by simondeziel** [comment]
@tomponline https://github.com/canonical/lxd-ci/actions/runs/12035105813/job/33553318964?pr=362#step:11:1115 looks suspicious as the stop hook is just not returning inside the allocated 10m.

**Comment by tomponline** [comment]
> @tomponline https://github.com/canonical/lxd-ci/actions/runs/12035105813/job/33553318964?pr=362#step:11:1115 looks suspicious as the stop hook is just not returning inside the allocated 10m.

Can we see the lxd debug logs (they dont seem to be in the lxd logs section)

**Comment by simondeziel** [comment]
It seems to have been a fluke as now it's stopping in ~1m.

> Can we see the lxd debug logs (they dont seem to be in the lxd logs section)

That is correct, debug logging is not enabled. Should I add the needed `snap set lxd` bit in `bin/helpers`' `install_lxd()` to unconditionally enable debug logging?

**Comment by tomponline** [comment]
> It seems to have been a fluke as now it's stopping in ~1m.
> 
> > Can we see the lxd debug logs (they dont seem to be in the lxd logs section)
> 
> That is correct, debug logging is not enabled. Should I add the needed `snap set lxd` bit in `bin/helpers`' `install_lxd()` to unconditionally enable debug logging?

Yeah we could try that and see how it goes

**Review by tomponline — APPROVED** [review]
Ta!

**Pull request merged**
