### PR TITLE
Fix intermittent failure on snapd seed

### PR DESCRIPTION
**Pull request by markylaing**
The `devlxd-container` tests are timing out when waiting for snapd to be seeded inside the container that will run a nested LXD.

This PR calls `waitInstanceBooted` after the container starts, then waits indefinitely for snap to be seeded. This approach is that same as in the `cluster` test.

### CODE REVIEW

**Comment by markylaing** [comment]
@tomponline well increasing the timeout doesn't fix it unfortunately: https://github.com/canonical/lxd-ci/actions/runs/10218115715/job/28273490182?pr=253#step:8:496

Do you know of any reason why snapd will take so long to seed? This is inside an `ubuntu-minimal-daily:24.04` container with `security.nesting=true`.

**Comment by tomponline** [comment]
> Do you know of any reason why snapd will take so long to seed? This is inside an `ubuntu-minimal-daily:24.04` container with `security.nesting=true`.

Are there any other tests where we wait for snapd to seed, can you look what is the difference here, perhaps it is nesting or the presence of /dev/lxd?

**Comment by markylaing** [comment]
> Are there any other tests where we wait for snapd to seed, can you look what is the difference here, perhaps it is nesting or the presence of /dev/lxd?

It looks like in `tests/cluster` we wait for the snapd seed indefinitely after calling `waitInstanceBooted`. I've just updated the test follow the same pattern.

**Comment by markylaing** [comment]
@tomponline I think this is good to go now.

**Review by tomponline — APPROVED** [review]

**Pull request merged**
