### PR TITLE
Tests: Check custom storage volume snapshots

### PR DESCRIPTION
**Pull request by roosterfish**
This now tests if custom volumes can be snapshotted, copied and transferred both locally and using a remote as well as between the same and different storage drivers.

Follow up on https://github.com/canonical/lxd-ci/pull/138.

### CODE REVIEW

**Comment by tomponline** [comment]
@markylaing any idea on this error?

https://github.com/canonical/lxd-ci/actions/runs/8646104028/job/23704697827?pr=139

```
+ lxc remote add localhost eyJjbGllbnRfbmFtZSI6ImxvY2FsaG9zdCIsImZpbmdlcnByaW50IjoiZWI1ZDk3Yzg5M2M4YTJiYTEwNmQ2ZWFhYmVmM2VlZWNkZDNiMTQzZTFmNzQ2YzFlYmU1NmI0MTkwZmEzMTBkZSIsImFkZHJlc3NlcyI6WyIxMC4xLjAuMTg3Ojg0NDMiLCIxMC4xMTAuMjQ0LjE6ODQ0MyIsIltmZDQyOmNiYTg6OTkxOTphZGI2OjoxXTo4NDQzIl0sInNlY3JldCI6ImI5ZDE1NDU0N2Q5NjA5YzNiMzdjZGRlMzc4NzM0NjRjODA4NmNlMjE3YjcwYWExNTY5NjIwYzllNjg4MjJmZDYiLCJleHBpcmVzX2F0IjoiMDAwMS0wMS0wMVQwMDowMDowMFoifQ== --accept-certificate
Error: Failed to create certificate: Invalid certificate type
```

**Comment by roosterfish** [comment]
Mhh, I was just checking this and think I have to change it.

Currently it removes only the remote, but the trust (`lxc config trust ls`) is still intact from the previous test run. Might this lead to the error?

**Comment by tomponline** [comment]
@roosterfish ready for review? Failures expected?

**Comment by roosterfish** [comment]
> @roosterfish ready for review? Failures expected?

Sorry, forgot to put in draft, it needs a bit more attention.

But ultimately I was wondering if we even need to have this here, as we have an abundance of custom storage volume tests over in the `lxd` repo. Wasn't thinking about this when checking for the existence of custom storage volume tests earlier today.

Maybe it would be more suitable to extend the tests there if something is missing?

**Comment by tomponline** [comment]
> Maybe it would be more suitable to extend the tests there if something is missing?

Yeah I would be happy to have these tests in the main test suite if suitable as we would catch issues sooner.

But we should check for both filesystem and block type volumes.

**Comment by tomponline** [comment]
In retrospect these volume tests are really testing that they can be attached to VMs

**Comment by tomponline** [comment]
@roosterfish looking at it, this part https://github.com/canonical/lxd-ci/blob/main/tests/storage-volumes-vm#L149-L158 would make more sense in https://github.com/canonical/lxd-ci/blob/main/tests/storage-vm as its to do with publishing VM instances and not custom volumes.

**Comment by roosterfish** [comment]
> @roosterfish looking at it, this part https://github.com/canonical/lxd-ci/blob/main/tests/storage-volumes-vm#L149-L158 would make more sense in https://github.com/canonical/lxd-ci/blob/main/tests/storage-vm as its to do with publishing VM instances and not custom volumes. Wouldn't it?

I agree as it's not attaching anything as the other tests do. 

I'll rework the PR to keep the trust removal for the `storage-vm` suite and move this test over.

**Comment by tomponline** [comment]
@roosterfish ready for review?

**Comment by roosterfish** [comment]
> @roosterfish ready for review?

Yes, pipelines are done now. As planned the `storage-vm` test for `latest/edge` is now succeeding after https://github.com/canonical/lxd/pull/13305 got merged yesterday.

**Review by tomponline — APPROVED** [review]

**Pull request merged**
