### PR TITLE
tests/network: switch from 23.10 (EOL) to 24.04 (LTS)

### PR DESCRIPTION
**Pull request by simondeziel**

### CODE REVIEW

**Comment by simondeziel** [comment]
@tomponline `tests/network` is not tested on GHA (so all red in CI is to be ignored) as it requires SR-IOV NICs. We usually run it through testflinger (on `luma`) but testflinger is in downtime this week.

**Review by tomponline — APPROVED** [review]
We should get the non physical tests working in github too.

**Comment by simondeziel** [comment]
> We should get the non physical tests working in github too.

Just to be 100% sure, you are referring to the macvlan ones, right?

**Comment by tomponline** [comment]
Yeah anything that doesn't require a physical nic

**Pull request merged**
