### PR TITLE
bin: Update `tf-reserve` and `testflinger-run` for Nvidia AGX board

### PR DESCRIPTION
**Pull request by gabrielmougard**
* Reserving an NVIDIA ORIN board can be done with the following comments at the beginning of a test script:
```bash
# testflinger_queue: nvidia-jetson-agx-orin
# testflinger_img_url: https://cdimage.ubuntu.com/nvidia-tegra/ubuntu-server/jammy/daily-preinstalled/current/jammy-preinstalled-server-arm64+tegra-igx.img.xz
# testflinger_boot_media: usb
```

* `tf-reserve` has also been updated to take a `media` parameter. Example:
```bash
$ export LP_USER=gabrielmougard
$ tf-reserve  nvidia-jetson-agx-orin https://cdimage.ubuntu.com/nvidia-tegra/ubuntu-server/jammy/daily-preinstalled/current/jammy-preinstalled-server-arm64+tegra-igx.img.xz usb
```

## Resources

* How to flash an Nvidia AGX board: https://docs.google.com/document/d/1YhwbyWNGz4K8k8zsKhMBqbII5NkuD70cxCfOs5aPOl0/edit
* Target ORIN board on TF: https://certification.canonical.com/hardware/202306-31646/

### CODE REVIEW

**Review by simondeziel — APPROVED** [review]

**Review by tomponline — CHANGES_REQUESTED** [review]
Could you add some examples and those links to the tf readme please?

**Comment by tomponline** [comment]
Looks like we need a tf usage readme file...

**Review by simondeziel — COMMENTED** [review]
Thanks for the readme. I think it'd be a nice place to add a link to https://docs.google.com/document/d/11Kot68mnBY9Wq9DXRzTVrKpx5cMkkhBC5RrM51eyybY

**Comment by gabrielmougard** [comment]
@simondeziel Shouldn't we just include the content of this google doc in this README so that we have only one single source of truth to maintain ?

**Comment by simondeziel** [comment]
@gabrielmougard yeah indeed, good idea, thanks.

**Review by tomponline — APPROVED** [review]

**Pull request merged**
