### PR TITLE
tests/interception: add test for finit_module interception

### PR DESCRIPTION
**Pull request by mihalicyn**
https://github.com/canonical/lxd/pull/13151

### CODE REVIEW

**Review by simondeziel — APPROVED** [review]
LGTM but I didn't know the actual module file had to be present in the container trying to modprobe it. I guess it makes sense though.

In a real world scenario, the user would be expected to `apt-get install "linux-modules-$(uname -r)" "linux-modules-extra-$(uname -r)"`?

**Comment by mihalicyn** [comment]
> LGTM but I didn't know the actual module file had to be present in the container trying to modprobe it. I guess it makes sense though.

it has to be present, because we use this file from inside the container to get module name from it. Then we use this module name to load the module on the host using file from the host. The `finit_module` syscall operates on the file descriptor, not on the module name. In any case, the input from the user for us is the module file.

>In a real world scenario, the user would be expected to apt-get install "linux-modules-$(uname -r)" "linux-modules-extra-$(uname -r)" in the instance?

Absolutely.

**Comment by tomponline** [comment]
> LGTM but I didn't know the actual module file had to be present in the container trying to modprobe it. I guess it makes sense though.

The syscall doesn't include the module name - only the module file handle.

**Review by tomponline — APPROVED** [review]
This is great thanks.

Now we have this kernel module loading test, could you add something similar but tot test the non-ondemand mode is working (i.e just `linux.kernel_modules` defined)?

**Comment by mihalicyn** [comment]
> Now we have this kernel module loading test, could you add something similar but tot test the non-ondemand mode is working (i.e just `linux.kernel_modules` defined)?

yes, it's a good task to improve test coverage

**Pull request merged**
